development:
  adapter: postgresql
  encoding: utf8
  database: leetsheet_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: leetsheet_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: leetsheet_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST
